minimum_pre_commit_version: "2.9.3"
exclude: >
  (?x)^(
    config/.*|
    .*\.ipynb|
    .*\.html|
    .*\.htm|
    .*\.jl|
    .*\.csv|
    .*\.svg|
  )$
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --dont-order-by-type
  - repo: "https://github.com/psf/black"
    rev: "22.10.0"
    hooks:
      - id: "black"
        name: "Format code (black)"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.3.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"

  - repo: "https://gitlab.com/PyCQA/flake8"
    rev: "3.9.2"
    hooks:
      - id: "flake8"
        name: "Lint code (flake8)"
        additional_dependencies:
          - "flake8>=3.8.3"
          - "flake8-broken-line>=0.2.0"
          - "flake8-bugbear>=20.1.4"
          - "flake8-builtins>=1.5.3"
          - "flake8-comprehensions>=3.2.3"
          - "flake8-import-order>=0.18.1"
          - "flake8-mutable>=1.2.0"
          - "flake8-pie==0.7.2"
          - "flake8-quotes>=3.2.0"
          - "flake8-string-format>=0.3.0"
          - "flake8-tidy-imports>=4.1.0"
          - "flake8-variables-names>=0.0.3"
          - "pep8-naming>=0.11.1"

  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.982"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        verbose: true
        additional_dependencies:
         - types-attrs
         - types-dateparser
         - types-mock
         - types-python-dateutil
         - types-python-slugify
         - types-PyYAML
